package com.project.model.enums;

public enum ArticleStatus {
	SUBMITTED,  
	IRRELEVANT_BY_TOPIC, 
	WAITING_FOR_REVIEW, 
	IRRELEVANT_BY_TEXT, 
	ADD_ADDITIONAL_EDITOR,
	DO_MINOR_CHANGES, 
	DO_MAJOR_CHANGES,
	REJECTED_TECHNICAL_REASON,
	REJECTED, 
	ACCEPTED
}
