server:
  port: 8085
  address: 127.0.0.1
  ssl: 
    enabled: true
    protocol: TLS
    key-alias: naucnacentrala
    key-store: classpath:security/kps_naucna_centrala_keystore.jks
    key-store-password: sepstore
    key-store-type: JKS
    trust-store: classpath:security/kps_naucna_centrala_truststore.jks
    trust-store-password: sepstore
    trust-store-type: JKS
    client-auth: want 

security:
  require-ssl: true

spring.datasource: # Please adjust username, password, hostname, port and database name
  type: org.postgresql.jdbc2.optional.SimpleDataSource
  username: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/science_centerL?useSSL=false
  
spring:
  application:
    name: scienceCenter
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp: 
          use_jdbc_metadata_defaults: false
        jdbc:
          lob: 
            non_contextual_creation: true
  mail: 
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: isa.airflights.project@gmail.com
    password: isa.airflights.project12
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
    protocol: smtp
    test-connection: false

mail:
  smtp:
    debug: true

camunda.bpm.admin-user: 
  id: demo
  password: demo
    

   
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: https://localhost:8761/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 2
    securePort: ${server.port}
    securePortEnabled: true
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
    nonSecurePortEnabled: false
  